model:
  params:
    # 训练参数
    time_steps: 1000  # 时间步长度，从1~1000开始
    linear_start: 1e-4  # 线性beta的起点
    linear_end: 2e-2  # 线性beta的终点
    base_learning_rate: 5.0e-5
    batch_size: 32
    epoch: 1000
    image_directory: '/root/data/train/flower/img/jpg'
    text_directory: '/root/data/train/flower/text_flower'
    img_h: 256  # 图像的高
    img_w: 256  # 图像的宽
    vlb_Switch: True  # 是否重构ELBO损失
    v_posterior: 0  # 超参，用于最优方差与完全前向方差的插值
    original_elbo_weight: 0

    snap: 10  # 每多少代保留一次模型参数
    out_path: "output"  # 输出图像的路径
    out_num: 10  # 输出图像的数量

    device: "cuda"  # 设备
    pretrain_device: "cuda"  # 预训练模型的位置

    z_coef: 1          # 频域信息系数，范围1-0，0为纯sd，1为纯hyper
    z_in: 6             # 额外嵌入信息的通道数
    z_dim: 64           # 额外嵌入信息向量的大小
    z_layer: 6          # 额外信息编码的卷积层数
    mask_type: 1        # 决定掩码类型，1为高通滤波，保留高频，0为不做滤波处理，-1为低通滤波，保留低频
    mask_radius: 50     # 滤波掩码半径，取决于图像尺寸
    gaussian_mask: True    # 是否采用高斯掩码
    gen_txt_path: "flower_gen.txt"    # 生成所用的txt文件的位置

    # DDIM参数
    DDIM_Switch: True
    DDIM_timesteps: 200  # DDIM采样所用的时间步,用于在DDPM的时间步中插值
    DDIM_eta: 0  # 用于调整生成的确定性与不确定性，当eta=0时为确定性采样DDIM，当eta=1时为不确定采样表示DDPM，在0~1表示两种插值

    # VAE参数
    VAE_Switch: True
    VAE_path: '/root/pre_model/VAE/VAE.safetensors'
    VAE_config_path: '/root/pre_model/VAE/config.json'

    # CLIP参数
    CLIP_Switch: True  # 只能开启，未设置非文本的训练接口
    CLIP_path: '/root/pre_model/CLIP'

    # Unet参数
    Unet_config:
      params:
        use_checkpoint: True
        use_fp16: True
#        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 256
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 768  # 与文本编码后的最后一个维度保持一致
        # Hyper
        z_coef: 1  # 默认不启用hypernetwork层
        z_in: 6             # 额外嵌入信息的通道数
        z_dim: 64           # 额外嵌入信息向量的大小
        z_layer: 6          # 额外信息编码的卷积层数
#        legacy: False


